/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/admin-login` | `/admin-login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/student-login` | `/student-login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/student-register` | `/student-register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin-dashboard` | `/admin-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin-elections` | `/admin-elections`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin-profile` | `/admin-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin-students` | `/admin-students`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/elections` | `/elections`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/results` | `/results`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/admin-login` | `/admin-login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/student-login` | `/student-login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/student-register` | `/student-register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/admin-dashboard` | `/admin-dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/admin-elections` | `/admin-elections`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/admin-profile` | `/admin-profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/admin-students` | `/admin-students`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/elections` | `/elections`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/results` | `/results`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/admin-login${`?${string}` | `#${string}` | ''}` | `/admin-login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/student-login${`?${string}` | `#${string}` | ''}` | `/student-login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/student-register${`?${string}` | `#${string}` | ''}` | `/student-register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/admin-dashboard${`?${string}` | `#${string}` | ''}` | `/admin-dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/admin-elections${`?${string}` | `#${string}` | ''}` | `/admin-elections${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/admin-profile${`?${string}` | `#${string}` | ''}` | `/admin-profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/admin-students${`?${string}` | `#${string}` | ''}` | `/admin-students${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/elections${`?${string}` | `#${string}` | ''}` | `/elections${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/results${`?${string}` | `#${string}` | ''}` | `/results${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/admin-login` | `/admin-login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/student-login` | `/student-login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/student-register` | `/student-register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin-dashboard` | `/admin-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin-elections` | `/admin-elections`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin-profile` | `/admin-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin-students` | `/admin-students`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/elections` | `/elections`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/results` | `/results`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
